import { attribute, autoGeneratedHashKey, rangeKey, table } from "@aws/dynamodb-data-mapper-annotations";

@table("auditTable")
export class AuditTable {

    @autoGeneratedHashKey()
    public id?: string;

    @rangeKey({type: "Date", defaultProvider: () => new Date()})
    public createdAt?: Date;

    @attribute()
    public action!: string;
}
